---
title: "R Notebook"
output: html_notebook
---

```{r}
# Load simulated lightcurves from h5 file
library(rhdf5);
library(astsa)
h5ls("./data/train_data_set.h5")
```
```{r fig1, fig.height = 15, fig.width =10, fig.align = "center"}

band_lists = list("u","g","r","i","z","y")

df <- h5read("./data/train_data_set.h5", "/training_0")
time <- df$x #time

# True LC (DRW+Transfer functions)
LCs <- df$"true_LC"
true_LCs = t(LCs)

# Simulated observed LC
LCs <- df$y
obs_LCs = t(LCs)

#observation mask, 1 if observed, 0 if unobserved
mask <- df$mask
mask <- t(mask)

# Adjust the mean of the observed
for (i in seq_len(ncol(true_LCs))) {
  idx = which(mask[,i]==1)
  obs_LCs[idx, i] <- obs_LCs[idx, i]- mean(obs_LCs[idx, i]) + mean(true_LCs[,i])
}


#Plot the light curves
old_par <- par(mfrow = c(6, 1),   # 1 row, 6 columns
               mar   = c(2, 2, 1, 1))  # margins: bottom, left, top, right
# loop over the 6 columns
for(i in seq_len(ncol(true_LCs))) {
  plot(time, true_LCs[,i],
       type  = "l",
       main  = paste("Band-", band_lists[i]))
  
  points(time, obs_LCs[,i],
       col = "blue",
       cex = 1.2)      # slightly larger
}
```

```{r}
num = nrow(obs_LCs)
A = array(0, dim=c(6,6,num))
for (t in 1:num){
  for(i in 1:6){
    if(obs_LCs[t,i]>0){
      A[i,i,t] = 1
    }
  }
}

mu0 = matrix(0,6,1)
for(i in 1:6){
  idx = which(mask[,i]==1)
  mu0[i] = mean(obs_LCs[idx,i])
}

Sigma0 <- matrix(0.6, nrow = 6, ncol = 6)
# Set the diagonal entries to 1
diag(Sigma0) <- 1
Phi = diag(1,6)
cQ = diag(0.05,6)
cR = diag(0.05,6)

em = EM(obs_LCs[,1:6], A, mu0,Sigma0,Phi,cQ,cR,Ups = NULL, Gam = NULL, input = NULL,max.iter = 100, tol = 1e-04)
```
```{r}
summary(em)
```

```{r}
em$Sigma0
```
```{r fig2, fig.height = 15, fig.width =10, fig.align = "center"}
smoother = Ksmooth(obs_LCs[,1:6], A, em$mu0, em$Sigma0, em$Phi, em$Q, em$R, Ups = NULL, Gam = NULL, 
         input = NULL, S = NULL, version = 1)
smoothed_mat   <- smoother$Xs[, 1, ]   # now a p × n matrix (here 6 × 4015)
Ps        <- smoother$Ps 
#Plot the light curves
old_par <- par(mfrow = c(6, 1),   # 1 row, 6 columns
               mar   = c(2, 2, 1, 1))  # margins: bottom, left, top, right

# loop over the 6 columns
for(i in seq_len(ncol(true_LCs))) {
  plot(time, true_LCs[,i],
     type  = "l",
     main  = paste("Band-", band_lists[i]))
  
  mu    <- smoothed_mat[i, ]
  se    <- sqrt(Ps[i, i, ])
  upper <- mu + 1.96 * se
  lower <- mu - 1.96 * se
  
  polygon(c(time, rev(time)),
        c(upper, rev(lower)),
        col = gray(0.7, alpha = 0.5),
        border = NA)
  
  lines(time,mu, lwd = 2, lty = 2, col = "red")
  
  points(time, obs_LCs[,i],
       col = "blue",
       cex = 1.2)      # slightly larger
  
  legend("topright",
       legend = c("True LC", "Smoothed","Observed"),
       lty    = c(1, 2),
       col    = c("black", "red", "blue"),
       bty    = "n")
}
```
```{r}
library(RcppCNPy)
npySave("smoothed_mat_2.npy", smoothed_mat)
npySave("Ps_2.npy", Ps)
```


